# Generated by Django 5.2.16 on 2026-07-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Firmenname')),
                ('street1', models.CharField(blank=True, max_length=255, verbose_name='Straße & Hausnummer')),
                ('street2', models.CharField(blank=True, max_length=255, verbose_name='Adresszusatz')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Ort')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Land')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Steuernummer')),
                ('vat_id', models.CharField(blank=True, max_length=50, verbose_name='USt-ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('etsy_shop_url', models.URLField(blank=True, verbose_name='Etsy-Shop')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Firmenprofil',
                'verbose_name_plural': 'Firmenprofil',
            },
        ),
    ]
