# Generated by Django 5.2.16 on 2026-07-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keep_count', models.PositiveIntegerField(default=3, verbose_name='Anzahl aufzubewahrender Backups')),
            ],
            options={
                'verbose_name': 'Backup-Einstellungen',
                'verbose_name_plural': 'Backup-Einstellungen',
            },
        ),
    ]
