# Generated by Django 5.2.16 on 2026-07-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gemstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gemstones/', verbose_name='Bild')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('alternative_names', models.CharField(blank=True, max_length=500, verbose_name='Alternative Namen')),
                ('origin', models.CharField(blank=True, max_length=255, verbose_name='Herkunft')),
                ('confusable_with', models.CharField(blank=True, max_length=500, verbose_name='Verwechslungen')),
                ('counterfeits', models.CharField(blank=True, max_length=500, verbose_name='Fälschungen')),
                ('mineral_class', models.CharField(blank=True, max_length=255, verbose_name='Mineralklasse')),
                ('chemical_composition', models.CharField(blank=True, max_length=255, verbose_name='Chemische Zusammensetzung')),
                ('formation', models.TextField(blank=True, verbose_name='Entstehung')),
                ('crystal_system', models.CharField(blank=True, max_length=100, verbose_name='Kristallsystem')),
                ('mohs_hardness', models.CharField(blank=True, max_length=50, verbose_name='Mohshärte')),
                ('density', models.CharField(blank=True, max_length=100, verbose_name='Dichte')),
                ('cleavage', models.CharField(blank=True, max_length=255, verbose_name='Spaltbarkeit')),
                ('fracture', models.CharField(blank=True, max_length=255, verbose_name='Bruchverhalten')),
                ('transparency', models.CharField(blank=True, max_length=100, verbose_name='Transparenz')),
                ('color', models.CharField(blank=True, max_length=255, verbose_name='Farbe')),
                ('luster', models.CharField(blank=True, max_length=100, verbose_name='Glanz')),
                ('streak', models.CharField(blank=True, max_length=100, verbose_name='Strichfarbe')),
                ('organ_effect', models.TextField(blank=True, verbose_name='Organwirkung')),
                ('physical_effect', models.TextField(blank=True, verbose_name='Körperliche Wirkung')),
                ('emotional_effect', models.TextField(blank=True, verbose_name='Seelische Wirkung')),
                ('application', models.TextField(blank=True, verbose_name='Anwendung')),
                ('bach_flower', models.CharField(blank=True, max_length=255, verbose_name='Ergänzende Bachblüte')),
                ('astrological_sign', models.CharField(blank=True, max_length=255, verbose_name='Astrologische Zuordnung')),
                ('chakra', models.CharField(blank=True, max_length=255, verbose_name='Chakra-Zuordnung')),
                ('feng_shui', models.CharField(blank=True, max_length=255, verbose_name='Feng-Shui-Zuordnung')),
                ('care_instructions', models.TextField(blank=True, verbose_name='Pflege')),
                ('notes', models.TextField(blank=True, verbose_name='Hinweise/Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Heilstein',
                'verbose_name_plural': 'Heilsteine',
                'ordering': ['name'],
            },
        ),
    ]
