# Generated by Django 5.2.16 on 2026-07-14 16:10

import mimetypes
import os

from django.db import migrations, models


def copy_image_files_into_blob(apps, schema_editor):
    """Reads whatever file each Gemstone.image currently points at (the
    shared MEDIA_ROOT) and copies its bytes into the new image_data/
    image_content_type/image_filename fields, before the old `image` field
    is dropped below - so the one existing entry's picture isn't silently
    lost in the process."""
    Gemstone = apps.get_model("lexikon", "Gemstone")
    db_alias = schema_editor.connection.alias
    for gemstone in Gemstone.objects.using(db_alias).exclude(image=""):
        if not gemstone.image:
            continue
        try:
            gemstone.image.open("rb")
            data = gemstone.image.read()
        except (FileNotFoundError, ValueError):
            continue
        finally:
            gemstone.image.close()
        gemstone.image_data = data
        gemstone.image_filename = os.path.basename(gemstone.image.name)
        gemstone.image_content_type = mimetypes.guess_type(gemstone.image.name)[0] or "application/octet-stream"
        gemstone.save(using=db_alias, update_fields=["image_data", "image_filename", "image_content_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('lexikon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemstone',
            name='image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Bild-Content-Type'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='image_data',
            field=models.BinaryField(blank=True, editable=False, null=True, verbose_name='Bilddaten'),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='image_filename',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Bild-Dateiname'),
        ),
        migrations.RunPython(copy_image_files_into_blob, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='gemstone',
            name='image',
        ),
    ]
