# Generated by Django 5.2.16 on 2026-07-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('sale_date', models.DateField()),
                ('date_shipped', models.DateField(blank=True, null=True)),
                ('number_of_items', models.PositiveIntegerField(default=1)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_type', models.CharField(blank=True, max_length=100)),
                ('order_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('buyer_username', models.CharField(blank=True, max_length=255)),
                ('ship_street1', models.CharField(blank=True, max_length=255)),
                ('ship_street2', models.CharField(blank=True, max_length=255)),
                ('ship_city', models.CharField(blank=True, max_length=255)),
                ('ship_state', models.CharField(blank=True, max_length=255)),
                ('ship_zipcode', models.CharField(blank=True, max_length=20)),
                ('ship_country', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_code', models.CharField(blank=True, max_length=100)),
                ('coupon_details', models.CharField(blank=True, max_length=255)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_processing_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adjusted_order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_card_processing_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_net_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inperson_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inperson_location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contacts.customer')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_raw', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=1)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.article')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['order', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('date_reviewed', models.DateField()),
                ('star_rating', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
            ],
            options={
                'ordering': ['-date_reviewed'],
            },
        ),
    ]
