# Generated by Django 5.2.16 on 2026-07-10 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('orders', '0002_order_archived_at_order_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='knowledge.packagingtype'),
        ),
    ]
