# Generated by Django 5.2.16 on 2026-07-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_article_options_alter_article_archived_at_and_more'),
        ('contacts', '0003_alter_customer_options_alter_supplier_options_and_more'),
        ('knowledge', '0003_alter_customstariffcode_options_and_more'),
        ('orders', '0003_alter_order_package_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Bestellung', 'verbose_name_plural': 'Bestellungen'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order', 'position'], 'verbose_name': 'Bestellposition', 'verbose_name_plural': 'Bestellpositionen'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_reviewed'], 'verbose_name': 'Bewertung', 'verbose_name_plural': 'Bewertungen'},
        ),
        migrations.AlterField(
            model_name='order',
            name='adjusted_card_processing_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Korrigierte Kartengebühren'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adjusted_net_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Korrigierter Netto-Bestellwert'),
        ),
        migrations.AlterField(
            model_name='order',
            name='adjusted_order_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Korrigierte Bestellsumme'),
        ),
        migrations.AlterField(
            model_name='order',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Etsy-Benutzername'),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_processing_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kartengebühren'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gutscheincode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon_details',
            field=models.CharField(blank=True, max_length=255, verbose_name='Gutschein-Details'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Währung'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contacts.customer', verbose_name='Kunde'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_shipped',
            field=models.DateField(blank=True, null=True, verbose_name='Versendet am'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rabattbetrag'),
        ),
        migrations.AlterField(
            model_name='order',
            name='inperson_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vor-Ort-Rabatt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='inperson_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vor-Ort-Standort'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archiviert'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_items',
            field=models.PositiveIntegerField(default=1, verbose_name='Anzahl Artikel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Bestell-ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Netto-Bestellwert'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bestellsumme'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bestellart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bestellwert'),
        ),
        migrations.AlterField(
            model_name='order',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='knowledge.packagingtype', verbose_name='Versendet als'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zahlungsmethode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zahlungsart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_date',
            field=models.DateField(verbose_name='Verkaufsdatum'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Umsatzsteuer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bundesland/Region'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_street1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Straße & Hausnummer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_street2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresszusatz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Versandkosten'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Versandunternehmen'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Versandrabatt'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sendungsnummer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.article', verbose_name='Artikel'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Bestellung'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku_raw',
            field=models.CharField(blank=True, max_length=255, verbose_name='SKU (roh)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_reviewed',
            field=models.DateField(verbose_name='Bewertungsdatum'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order', verbose_name='Bestellung'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(max_length=255, verbose_name='Rezensent'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.PositiveSmallIntegerField(verbose_name='Sternebewertung'),
        ),
    ]
