# Generated by Django 5.2.16 on 2026-07-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='etsy_order_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Etsy-Bestellnummer'),
        ),
    ]
