# Generated by Django 5.2.16 on 2026-07-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_etsy_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='etsy_receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/bestellungen/', verbose_name='Etsy-Bestellbeleg'),
        ),
        migrations.AddField(
            model_name='order',
            name='outgoing_invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/finanzen/ausgangsrechnungen/', verbose_name='Ausgangsrechnung'),
        ),
    ]
