# Generated by Django 5.2.16 on 2026-07-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_etsy_receipt_file_order_outgoing_invoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='outgoing_invoice_file',
        ),
    ]
