# Generated by Django 5.2.16 on 2026-07-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_outgoing_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Etsy-Artikelname'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='listing_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Etsy-Listing-ID'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis (Etsy, pro Stück)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Menge'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.CharField(blank=True, max_length=255, verbose_name='Variante (Etsy)'),
        ),
    ]
