# Generated by Django 5.2.16 on 2026-07-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_item_name_orderitem_listing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sku_raw',
            field=models.CharField(blank=True, max_length=255, verbose_name='Etsy-SKU (roh)'),
        ),
    ]
