# Generated by Django 5.2.16 on 2026-07-14 22:53

import os

import orders.models
from django.db import migrations, models


def move_receipt_files_into_year_folders(apps, schema_editor):
    """Bestehende Bestellbelege lagen bisher flach in einem gemeinsamen Ordner
    - verschiebt sie nach documents/bestellungen/<jahr>/<datei>, passend zum
    neuen upload_to, und aktualisiert den gespeicherten Pfad."""
    Order = apps.get_model("orders", "Order")
    db_alias = schema_editor.connection.alias

    for order in Order.objects.using(db_alias).exclude(etsy_receipt_file=""):
        field_file = order.etsy_receipt_file
        old_name = field_file.name
        if not old_name:
            continue
        year = order.sale_date.year if order.sale_date else "unbekannt"
        new_name = f"documents/bestellungen/{year}/{os.path.basename(old_name)}"
        if new_name == old_name:
            continue
        storage = field_file.storage
        if not storage.exists(old_name):
            continue
        with storage.open(old_name, "rb") as f:
            storage.save(new_name, f)
        storage.delete(old_name)
        order.etsy_receipt_file = new_name
        order.save(using=db_alias, update_fields=["etsy_receipt_file"])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_sku_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='etsy_receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=orders.models.order_receipt_path, verbose_name='Etsy-Bestellbeleg'),
        ),
        migrations.RunPython(move_receipt_files_into_year_folders, migrations.RunPython.noop),
    ]
