# Generated by Django 5.2.16 on 2026-08-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_etsy_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Bestell-ID'),
        ),
    ]
