# Generated by Django 5.2.16 on 2026-07-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('street1', models.CharField(blank=True, max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'E-Mail'), ('phone', 'Telefon'), ('etsy', 'Etsy-Nachricht'), ('post', 'Post')], max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('last_contact_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('lead', 'Lead'), ('paused', 'Pausiert'), ('completed', 'Abgeschlossen')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etsy_buyer_user_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_returning_customer', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['full_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('street1', models.CharField(blank=True, max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'E-Mail'), ('phone', 'Telefon'), ('etsy', 'Etsy-Nachricht'), ('post', 'Post')], max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('last_contact_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('lead', 'Lead'), ('paused', 'Pausiert'), ('completed', 'Abgeschlossen')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.URLField(blank=True)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('vat_id', models.CharField(blank=True, max_length=50)),
                ('standard_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['full_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierDiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_tiers', to='contacts.supplier')),
            ],
            options={
                'ordering': ['supplier', 'min_order_value'],
            },
        ),
    ]
