# Generated by Django 5.2.16 on 2026-07-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_customer_archived_at_customer_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['full_name'], 'verbose_name': 'Kunde', 'verbose_name_plural': 'Kunden'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['full_name'], 'verbose_name': 'Lieferant', 'verbose_name_plural': 'Lieferanten'},
        ),
        migrations.AlterModelOptions(
            name='supplierdiscounttier',
            options={'ordering': ['supplier', 'min_order_value'], 'verbose_name': 'Rabattstaffel', 'verbose_name_plural': 'Rabattstaffeln'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtstag'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='etsy_buyer_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Etsy-Käufer-ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Vollständiger Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archiviert'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_returning_customer',
            field=models.BooleanField(default=False, verbose_name='Stammkunde'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_contact_at',
            field=models.DateField(blank=True, null=True, verbose_name='Letzter Kontakt'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bevorzugte Kontaktart'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bundesland/Region'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, default='Aktiv', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Straße & Hausnummer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresszusatz'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kundennummer beim Lieferanten'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtstag'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Vollständiger Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archiviert'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_contact_at',
            field=models.DateField(blank=True, null=True, verbose_name='Letzter Kontakt'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lieferzeit (Tage)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, verbose_name='Zahlungsziel'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='contacts.supplier', verbose_name='Plattform'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bevorzugte Kontaktart'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='standard_discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Standard-Rabatt (%)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bundesland/Region'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, default='Aktiv', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='street1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Straße & Hausnummer'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='street2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresszusatz'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='vat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='USt-ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='supplierdiscounttier',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rabatt (%)'),
        ),
        migrations.AlterField(
            model_name='supplierdiscounttier',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mindestbestellwert'),
        ),
        migrations.AlterField(
            model_name='supplierdiscounttier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_tiers', to='contacts.supplier', verbose_name='Lieferant'),
        ),
    ]
