# Generated by Django 5.2.16 on 2026-07-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_split_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nachname'),
        ),
    ]
