# Generated by Django 5.2.16 on 2026-08-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am')),
                ('article_number', models.CharField(blank=True, max_length=100, verbose_name='Artikel-Nr.')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Artikel')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Anzahl')),
                ('price_each', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis (einzeln)')),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preis (gesamt)')),
                ('image_url', models.URLField(blank=True, verbose_name='Bild (Link)')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='Händler')),
                ('shop_url', models.URLField(blank=True, verbose_name='Shopseite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Einkaufslisten-Eintrag',
                'verbose_name_plural': 'Einkaufsliste',
                'ordering': ['supplier_name', 'title'],
            },
        ),
    ]
