# Generated by Django 5.2.16 on 2026-08-02 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_supplier_first_name_alter_supplier_last_name'),
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'ordering': ['supplier__last_name', 'supplier__first_name', 'title'], 'verbose_name': 'Einkaufslisten-Eintrag', 'verbose_name_plural': 'Einkaufsliste'},
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_list_items', to='contacts.supplier', verbose_name='Händler'),
        ),
        migrations.CreateModel(
            name='ShoppingListItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Bild-Link')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Reihenfolge')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopping_list.shoppinglistitem', verbose_name='Eintrag')),
            ],
            options={
                'verbose_name': 'Einkaufslisten-Bild',
                'verbose_name_plural': 'Einkaufsliste-Bilder',
                'ordering': ['item', 'position'],
            },
        ),
    ]
