# Generated by Django 5.2.16 on 2026-07-10 13:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_customer_archived_at_customer_is_archived_and_more'),
        ('orders', '0002_order_archived_at_order_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKR03Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=4)),
                ('supplier_order_number', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/expenses/')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateField(blank=True, null=True)),
                ('cancellation_invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/cancellations/')),
                ('payment_account', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, default='Offen', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='contacts.supplier')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('info', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fees_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_info', models.CharField(blank=True, max_length=255)),
                ('etsy_listing_ref', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('import', 'Import'), ('manual', 'Manuell')], default='import', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=100)),
                ('variante', models.CharField(blank=True, max_length=100)),
                ('skr03_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.skr03account')),
            ],
            options={
                'ordering': ['art', 'variante'],
                'unique_together': {('art', 'variante')},
            },
        ),
    ]
