# Generated by Django 5.2.16 on 2026-07-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Ledger entries'},
        ),
    ]
