# Generated by Django 5.2.16 on 2026-07-10 14:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_customer_options_alter_supplier_options_and_more'),
        ('finance', '0002_alter_ledgerentry_options'),
        ('orders', '0003_alter_order_package_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmapping',
            options={'ordering': ['art', 'variante'], 'verbose_name': 'Konten-Zuordnung', 'verbose_name_plural': 'Konten-Zuordnungen'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Ausgabe', 'verbose_name_plural': 'Ausgaben'},
        ),
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-date'], 'verbose_name': 'Buchung', 'verbose_name_plural': 'Buchungen'},
        ),
        migrations.AlterModelOptions(
            name='skr03account',
            options={'ordering': ['number'], 'verbose_name': 'SKR03-Konto', 'verbose_name_plural': 'SKR03-Konten'},
        ),
        migrations.AlterField(
            model_name='accountmapping',
            name='art',
            field=models.CharField(max_length=100, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='accountmapping',
            name='skr03_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.skr03account', verbose_name='SKR03-Konto'),
        ),
        migrations.AlterField(
            model_name='accountmapping',
            name='variante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Variante'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag (brutto)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cancellation_invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/cancellations/', verbose_name='Stornorechnung (Datei)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='cancelled_at',
            field=models.DateField(blank=True, null=True, verbose_name='Storniert am'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rechnungsdatum'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/expenses/', verbose_name='Rechnung (Datei)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rechnungsnummer'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archiviert'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Storniert'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zahlungskonto'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(blank=True, default='Offen', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='contacts.supplier', verbose_name='Lieferant'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier_order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bestell-Nr. beim Lieferanten'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='variant',
            field=models.CharField(blank=True, max_length=100, verbose_name='Variante'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=4, verbose_name='USt-Satz (%)'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Währung'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(max_length=100, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='etsy_listing_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etsy-Artikel-Nr.'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='fees_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gebühren & Steuern'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Netto'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order', verbose_name='Bestellung'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='source',
            field=models.CharField(choices=[('import', 'Import'), ('manual', 'Manuell')], default='import', max_length=10, verbose_name='Quelle'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='tax_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Steuerliche Angaben'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='skr03account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='skr03account',
            name='number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kontonummer'),
        ),
    ]
