# Generated by Django 5.2.16 on 2026-07-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_accountmapping_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cancellation_invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/finanzen/eingangsrechnungen/storno/', verbose_name='Stornorechnung (Datei)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/finanzen/eingangsrechnungen/', verbose_name='Rechnung (Datei)'),
        ),
    ]
