# Generated by Django 5.2.16 on 2026-07-12 22:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_supplier_first_name_alter_supplier_last_name'),
        ('finance', '0004_alter_expense_cancellation_invoice_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archiviert')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am')),
                ('date', models.DateField(verbose_name='Datum')),
                ('category', models.CharField(max_length=100, verbose_name='Kategorie')),
                ('variant', models.CharField(blank=True, max_length=100, verbose_name='Variante')),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag (brutto)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=4, verbose_name='USt-Satz (%)')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Rechnungsnummer')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Rechnungsdatum')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='documents/finanzen/ausgangsrechnungen/', verbose_name='Rechnung (Datei)')),
                ('payment_account', models.CharField(blank=True, max_length=50, verbose_name='Zahlungskonto')),
                ('status', models.CharField(blank=True, default='Offen', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='contacts.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Einnahme',
                'verbose_name_plural': 'Einnahmen',
                'ordering': ['-date'],
            },
        ),
    ]
