# Generated by Django 5.2.16 on 2026-07-12 23:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='cancellation_invoice_file',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_account',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='supplier_order_number',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vat_rate',
        ),
        migrations.AddField(
            model_name='expense',
            name='account_debit_actual_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Konto-Belastung (Ist, EUR)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='account_debit_target_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Konto-Belastung (Soll, EUR)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='amount_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Rechnungsbetrag (EUR)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Währung (Original)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Ausgaben-ID'),
        ),
        migrations.AddField(
            model_name='expense',
            name='fx_fee_fixed_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='FX-Gebühr Fix (EUR)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='fx_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='FX-Gebühr (%)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='fx_rate_eur_per_original',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('1'), max_digits=14, verbose_name='FX-Kurs (EUR je 1 Original)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='fx_rate_original_per_eur',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('1'), max_digits=14, verbose_name='FX-Kurs (Original je 1 EUR)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='gross_0',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Brutto 0%'),
        ),
        migrations.AddField(
            model_name='expense',
            name='gross_19',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Brutto 19%'),
        ),
        migrations.AddField(
            model_name='expense',
            name='gross_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Brutto 7%'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_eu',
            field=models.BooleanField(default=False, verbose_name='EU'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_third_country',
            field=models.BooleanField(default=False, verbose_name='Drittland'),
        ),
        migrations.AddField(
            model_name='expense',
            name='net_0',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Netto 0%'),
        ),
        migrations.AddField(
            model_name='expense',
            name='net_19',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Netto 19%'),
        ),
        migrations.AddField(
            model_name='expense',
            name='net_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Netto 7%'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Zahlungsdatum (Bezahlt)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zahlungsart'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_19_invoice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='USt 19% (lt. Rechnung)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_7_invoice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='USt 7% (lt. Rechnung)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Betrag (Original)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Art'),
        ),
    ]
