# Generated by Django 5.2.16 on 2026-07-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_expense_cancellation_invoice_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='account_debit_target_eur',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount_eur',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='net_0',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='net_19',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='net_7',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vat_19_invoice',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vat_7_invoice',
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_rate',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (7, '7%'), (19, '19%')], default=19, verbose_name='USt-Satz'),
        ),
    ]
