# Generated by Django 5.2.16 on 2026-07-13 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_replace_skr03_seed_data'),
        ('orders', '0009_alter_orderitem_sku_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.RemoveField(
            model_name='income',
            name='variant',
        ),
        migrations.AddField(
            model_name='income',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='orders.order', verbose_name='Bestellung'),
        ),
        migrations.AddField(
            model_name='income',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geldeingang'),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zahlungsart'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rechnungsbetrag (brutto)'),
        ),
        migrations.AlterField(
            model_name='income',
            name='invoice_number',
            field=models.CharField(max_length=100, verbose_name='Rechnungsnummer'),
        ),
        migrations.AlterField(
            model_name='income',
            name='vat_rate',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (7, '7%'), (19, '19%')], default=19, verbose_name='USt-Satz'),
        ),
    ]
