# Generated by Django 5.2.16 on 2026-07-13 15:51

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_income_description_remove_income_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('period_label', models.CharField(help_text='z.B. Q1, Juni, Jahresbericht', max_length=50, verbose_name='Zeitraum')),
                ('file', models.FileField(upload_to=finance.models.tax_report_path, verbose_name='Datei')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
            ],
            options={
                'verbose_name': 'USt-Bericht',
                'verbose_name_plural': 'USt-Berichte',
                'ordering': ['-year', 'period_label'],
            },
        ),
    ]
