# Generated by Django 5.2.16 on 2026-07-14 16:36

from django.db import migrations, models

# Nur exakte Monatsnamen (Gross-/Kleinschreibung egal) werden automatisch
# zugeordnet - alles andere (Datumsbereiche wie "01.08. - 31.08.", "Q1",
# "Jahresbericht" in freier Schreibweise, ...) bleibt bewusst unklar und wird
# auf NULL gesetzt, statt eine unsichere Vermutung anzuwenden.
MONTH_NAME_TO_CODE = {
    "januar": 1, "februar": 2, "märz": 3, "april": 4, "mai": 5, "juni": 6,
    "juli": 7, "august": 8, "september": 9, "oktober": 10, "november": 11, "dezember": 12,
}


def migrate_period_label_to_period(apps, schema_editor):
    TaxReport = apps.get_model("finance", "TaxReport")
    db_alias = schema_editor.connection.alias
    for report in TaxReport.objects.using(db_alias).all():
        code = MONTH_NAME_TO_CODE.get(report.period_label.strip().lower())
        if code:
            report.period = code
            report.save(using=db_alias, update_fields=["period"])


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_taxreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreport',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember'), (13, 'Q1 (Jan-Mrz)'), (14, 'Q2 (Apr-Jun)'), (15, 'Q3 (Jul-Sep)'), (16, 'Q4 (Okt-Dez)'), (17, 'Jahresbericht')], null=True, verbose_name='Zeitraum'),
        ),
        migrations.RunPython(migrate_period_label_to_period, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='taxreport',
            name='period_label',
        ),
        migrations.AlterModelOptions(
            name='taxreport',
            options={'ordering': ['-year', '-period'], 'verbose_name': 'USt-Bericht', 'verbose_name_plural': 'USt-Berichte'},
        ),
    ]
