# Generated by Django 5.2.16 on 2026-07-14 22:53

import os

import finance.models
from django.db import migrations, models


def _move_invoice_file(instance, field_name, base_dir, db_alias):
    field_file = getattr(instance, field_name)
    old_name = field_file.name
    if not old_name:
        return
    reference_date = instance.invoice_date or instance.date
    year = reference_date.year if reference_date else "unbekannt"
    new_name = f"{base_dir}/{year}/{os.path.basename(old_name)}"
    if new_name == old_name:
        return
    storage = field_file.storage
    if not storage.exists(old_name):
        return
    with storage.open(old_name, "rb") as f:
        storage.save(new_name, f)
    storage.delete(old_name)
    setattr(instance, field_name, new_name)
    instance.save(using=db_alias, update_fields=[field_name])


def move_invoice_files_into_year_folders(apps, schema_editor):
    """Bestehende Rechnungsdateien lagen bisher flach in einem gemeinsamen
    Ordner - verschiebt sie nach documents/finanzen/<...>/<jahr>/<datei>,
    passend zum neuen upload_to, und aktualisiert den gespeicherten Pfad."""
    db_alias = schema_editor.connection.alias
    Income = apps.get_model("finance", "Income")
    Expense = apps.get_model("finance", "Expense")

    for income in Income.objects.using(db_alias).exclude(invoice_file=""):
        _move_invoice_file(income, "invoice_file", "documents/finanzen/ausgangsrechnungen", db_alias)

    for expense in Expense.objects.using(db_alias).exclude(invoice_file=""):
        _move_invoice_file(expense, "invoice_file", "documents/finanzen/eingangsrechnungen", db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_taxreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to=finance.models.expense_invoice_path, verbose_name='Rechnung (Datei)'),
        ),
        migrations.AlterField(
            model_name='income',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to=finance.models.income_invoice_path, verbose_name='Rechnung (Datei)'),
        ),
        migrations.RunPython(move_invoice_files_into_year_folders, migrations.RunPython.noop),
    ]
