# Generated by Django 5.2.16 on 2026-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenceoption',
            options={'ordering': ['category', 'order', 'value'], 'verbose_name': 'Referenzwert', 'verbose_name_plural': 'Referenzwerte'},
        ),
        migrations.AlterField(
            model_name='referenceoption',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='referenceoption',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='referenceoption',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Wert'),
        ),
    ]
