# Generated by Django 5.2.16 on 2026-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsTariffCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('definition', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='knowledge/')),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('paper_kg_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('plastic_kg_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('glass_kg_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('valid_from', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('use_case', models.CharField(blank=True, max_length=255)),
                ('price_note', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('requires_tracking_number', models.BooleanField(default=False)),
                ('is_international', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['carrier', 'description'],
            },
        ),
    ]
