# Generated by Django 5.2.16 on 2026-07-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgeentry',
            options={'ordering': ['title'], 'verbose_name_plural': 'Knowledge entries'},
        ),
    ]
