# Generated by Django 5.2.16 on 2026-07-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_knowledgeentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customstariffcode',
            options={'ordering': ['code'], 'verbose_name': 'Zolltarifnummer', 'verbose_name_plural': 'Zolltarifnummern'},
        ),
        migrations.AlterModelOptions(
            name='knowledgeentry',
            options={'ordering': ['title'], 'verbose_name': 'Infothek-Eintrag', 'verbose_name_plural': 'Infothek-Einträge'},
        ),
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'ordering': ['name'], 'verbose_name': 'Verpackungsart', 'verbose_name_plural': 'Verpackungsarten'},
        ),
        migrations.AlterModelOptions(
            name='shippingoption',
            options={'ordering': ['carrier', 'description'], 'verbose_name': 'Versandoption', 'verbose_name_plural': 'Versandoptionen'},
        ),
        migrations.AlterField(
            model_name='customstariffcode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Zolltarifnummer'),
        ),
        migrations.AlterField(
            model_name='customstariffcode',
            name='definition',
            field=models.CharField(max_length=255, verbose_name='Definition'),
        ),
        migrations.AlterField(
            model_name='customstariffcode',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='content',
            field=models.TextField(blank=True, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='knowledge/', verbose_name='Beitragsbild'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='glass_kg_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Glas (kg pro Stück)'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='paper_kg_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Papier/Pappe/Karton (kg pro Stück)'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='plastic_kg_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Kunststoffe (kg pro Stück)'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig ab'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='carrier',
            field=models.CharField(max_length=100, verbose_name='Anbieter'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='is_international',
            field=models.BooleanField(default=False, verbose_name='International'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bezahlen'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='price_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='requires_tracking_number',
            field=models.BooleanField(default=False, verbose_name='Sendungsnummer nötig'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='use_case',
            field=models.CharField(blank=True, max_length=255, verbose_name='Anwendung'),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig ab'),
        ),
    ]
