# Generated by Django 5.2.16 on 2026-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_customstariffcode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gemstones/', verbose_name='Bild')),
                ('mohs_hardness', models.CharField(blank=True, max_length=50, verbose_name='Mohshärte')),
                ('origin', models.CharField(blank=True, max_length=255, verbose_name='Herkunft')),
                ('physical_properties', models.TextField(blank=True, verbose_name='Körperliche Wirkung')),
                ('emotional_properties', models.TextField(blank=True, verbose_name='Seelische/mentale Wirkung')),
                ('spiritual_properties', models.TextField(blank=True, verbose_name='Zusprechungen')),
                ('care_instructions', models.TextField(blank=True, verbose_name='Pflegehinweise')),
                ('symptoms', models.TextField(blank=True, verbose_name='Anwendungsgebiete/Symptome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Heilstein',
                'verbose_name_plural': 'Heilsteine',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='KnowledgeEntry',
        ),
    ]
