# Generated by Django 5.2.16 on 2026-07-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_gemstone_delete_knowledgeentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gemstone',
        ),
    ]
