# Generated by Django 5.2.16 on 2026-07-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_delete_gemstone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('price_per_kg', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Preis (€/kg)')),
            ],
            options={
                'verbose_name': 'Materialkategorie',
                'verbose_name_plural': 'Materialkategorien',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='packagingtype',
            name='glass_kg_per_unit',
        ),
        migrations.RemoveField(
            model_name='packagingtype',
            name='paper_kg_per_unit',
        ),
        migrations.RemoveField(
            model_name='packagingtype',
            name='plastic_kg_per_unit',
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100, verbose_name='Maße'),
        ),
        migrations.CreateModel(
            name='PackagingTypeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='kg pro Stück')),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knowledge.materialcategory', verbose_name='Materialkategorie')),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='knowledge.packagingtype', verbose_name='Verpackungsart')),
            ],
            options={
                'verbose_name': 'Verpackungsart-Material',
                'verbose_name_plural': 'Verpackungsart-Materialien',
                'ordering': ['packaging_type', 'material_category'],
                'unique_together': {('packaging_type', 'material_category')},
            },
        ),
    ]
