# Generated by Django 5.2.16 on 2026-07-11 18:11

from django.db import migrations

# Official VerpackG/LUCID material categories - price_per_kg starts at 0,
# to be filled in from the yearly Grüner Punkt invoice via the UI.
MATERIAL_CATEGORIES = [
    "Glas",
    "Pappe, Papier, Karton",
    "Eisenmetalle",
    "Aluminium",
    "Kunststoffe",
    "Getränkekartonverpackungen",
    "Sonstige Verbundverpackungen",
    "Sonstige Materialien",
]


def seed_categories(apps, schema_editor):
    MaterialCategory = apps.get_model("knowledge", "MaterialCategory")
    for name in MATERIAL_CATEGORIES:
        MaterialCategory.objects.get_or_create(name=name)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_materialcategory_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_categories, noop),
    ]
