# Generated by Django 5.2.16 on 2026-07-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_seed_material_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingtypematerial',
            name='material_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.materialcategory', verbose_name='Materialkategorie'),
        ),
    ]
