# Generated by Django 5.2.16 on 2026-07-11 21:33

import knowledge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_alter_packagingtypematerial_material_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingLicenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('doc_type', models.CharField(choices=[('rechnung', 'Rechnung'), ('vertragsblatt', 'Vertragsblatt'), ('teilnahmebestaetigung', 'Teilnahmebestätigung'), ('umweltzertifikat', 'Umweltzertifikat'), ('mitteilung', 'Mitteilung/Sonstiges')], max_length=30, verbose_name='Dokumenttyp')),
                ('file', models.FileField(upload_to=knowledge.models.packaging_license_document_path, verbose_name='Datei')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
            ],
            options={
                'verbose_name': 'Verpackungslizenz-Dokument',
                'verbose_name_plural': 'Verpackungslizenz-Dokumente',
                'ordering': ['-year', 'doc_type'],
            },
        ),
    ]
