# Generated by Django 5.2.16 on 2026-07-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_packaginglicensedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingLicenseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('submission_type', models.CharField(choices=[('jahresabschlussmeldung', 'Jahresabschlussmeldung'), ('planmengenanpassung', 'Planmengenanpassung')], max_length=30, verbose_name='Meldungsart')),
                ('submitted', models.BooleanField(default=False, verbose_name='Abgegeben')),
                ('submitted_at', models.DateField(blank=True, null=True, verbose_name='Abgegeben am')),
            ],
            options={
                'verbose_name': 'Verpackungslizenz-Meldung',
                'verbose_name_plural': 'Verpackungslizenz-Meldungen',
                'ordering': ['-year', 'submission_type'],
                'unique_together': {('year', 'submission_type')},
            },
        ),
    ]
