# Generated by Django 5.2.16 on 2026-07-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_packaginglicensesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaginglicensesubmission',
            name='submission_type',
            field=models.CharField(choices=[('jahresabschlussmeldung', 'Jahresabschlussmeldung'), ('planmengenanpassung', 'Planmengenanpassung'), ('lucid_meldung', 'LUCID-Datenmeldung')], max_length=30, verbose_name='Meldungsart'),
        ),
    ]
