# Generated by Django 5.2.16 on 2026-07-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_alter_packaginglicensesubmission_submission_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingLicenseDataReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(choices=[('lucid', 'LUCID'), ('gruener_punkt', 'Der Grüne Punkt')], max_length=20, verbose_name='Empfänger')),
                ('type_of_report_code', models.CharField(max_length=20, verbose_name='Meldungsart-Code')),
                ('reporting_period_from', models.DateField(verbose_name='Meldezeitraum von')),
                ('reporting_period_to', models.DateField(verbose_name='Meldezeitraum bis')),
                ('system_operator_id', models.CharField(blank=True, max_length=50, verbose_name='Systembeteiligungs-ID')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='documents/verpackungslizenz/xml/', verbose_name='Quelldatei')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Importiert am')),
            ],
            options={
                'verbose_name': 'Verpackungslizenz-Datenmeldung',
                'verbose_name_plural': 'Verpackungslizenz-Datenmeldungen',
                'ordering': ['-reporting_period_from'],
            },
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='lucid_material_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='LUCID-Materialcode'),
        ),
        migrations.CreateModel(
            name='PackagingLicenseDataReportMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=10, verbose_name='LUCID-Materialcode')),
                ('mass_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Masse (kg)')),
                ('material_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.materialcategory', verbose_name='Materialkategorie')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='knowledge.packaginglicensedatareport', verbose_name='Datenmeldung')),
            ],
            options={
                'verbose_name': 'Datenmeldung-Material',
                'verbose_name_plural': 'Datenmeldung-Materialien',
                'ordering': ['material_code'],
            },
        ),
    ]
