# Generated by Django 5.2.16 on 2026-07-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0013_seed_lucid_material_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaginglicensedatareportmaterial',
            name='mass_kg',
        ),
        migrations.AddField(
            model_name='packaginglicensedatareportmaterial',
            name='mass_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Menge (lt. XML, Einheit unbestätigt)'),
        ),
    ]
