# Generated by Django 5.2.16 on 2026-07-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0014_remove_packaginglicensedatareportmaterial_mass_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaginglicensedatareportmaterial',
            name='mass_value',
        ),
        migrations.AddField(
            model_name='packaginglicensedatareport',
            name='report_type',
            field=models.CharField(choices=[('unterjaehrige_mengenmeldung', 'Unterjährige Mengenmeldung'), ('jahresabschlussmengenmeldung', 'Jahresabschlussmengenmeldung'), ('initiale_planmengenmeldung', 'Initiale Planmengenmeldung'), ('nachtragsmengenmeldung', 'Nachtragsmengenmeldung'), ('sonstige', 'Sonstige/Unbekannt')], default='sonstige', max_length=30, verbose_name='Meldeart'),
        ),
        migrations.AddField(
            model_name='packaginglicensedatareportmaterial',
            name='mass_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Menge (kg)'),
        ),
        migrations.AlterField(
            model_name='packaginglicensedatareport',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erfasst am'),
        ),
        migrations.AlterField(
            model_name='packaginglicensedatareport',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/verpackungslizenz/xml/', verbose_name='Quelldatei (XML oder PDF)'),
        ),
        migrations.AlterField(
            model_name='packaginglicensedatareport',
            name='type_of_report_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Meldungsart-Code (XML)'),
        ),
        migrations.AlterField(
            model_name='packaginglicensedatareportmaterial',
            name='material_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='LUCID-Materialcode'),
        ),
    ]
