# Generated by Django 5.2.16 on 2026-07-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0015_remove_packaginglicensedatareportmaterial_mass_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaginglicensesubmission',
            name='submitted_at',
        ),
    ]
