# Generated by Django 5.2.16 on 2026-07-16 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='Bezeichnung')),
                ('birth_date', models.DateField(verbose_name='Geburtsdatum')),
                ('birth_time', models.TimeField(blank=True, null=True, verbose_name='Geburtszeit')),
                ('birth_place_raw', models.CharField(max_length=200, verbose_name='Geburtsort')),
                ('geonameid', models.CharField(blank=True, max_length=20, verbose_name='GeoNames-ID')),
                ('birth_lat', models.FloatField(blank=True, null=True, verbose_name='Breitengrad')),
                ('birth_lon', models.FloatField(blank=True, null=True, verbose_name='Längengrad')),
                ('birth_timezone', models.CharField(blank=True, max_length=64, verbose_name='Zeitzone')),
                ('house_system', models.CharField(choices=[('placidus', 'Placidus'), ('koch', 'Koch'), ('equal', 'Equal'), ('whole_sign', 'Whole Sign')], default='placidus', max_length=20, verbose_name='Häusersystem')),
                ('include_chiron', models.BooleanField(default=True, verbose_name='Chiron einbeziehen')),
                ('include_pholus', models.BooleanField(default=True, verbose_name='Pholus einbeziehen')),
                ('include_lilith', models.BooleanField(default=True, verbose_name='Lilith einbeziehen')),
                ('raw_positions', models.JSONField(blank=True, default=dict, verbose_name='Rohdaten (Ephemeride)')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='Berechnet am')),
            ],
            options={
                'verbose_name': 'Geburtshoroskop',
                'verbose_name_plural': 'Geburtshoroskope',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Hausnummer')),
                ('name_de', models.CharField(max_length=100, verbose_name='Name')),
                ('short_meaning', models.CharField(blank=True, max_length=200, verbose_name='Kurzbedeutung')),
            ],
            options={
                'verbose_name': 'Haus',
                'verbose_name_plural': 'Häuser',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Schlüssel')),
                ('name_de', models.CharField(max_length=50, verbose_name='Name')),
                ('is_angle', models.BooleanField(default=False, verbose_name='Achsenpunkt (Aszendent/MC)')),
                ('is_optional_body', models.BooleanField(default=False, verbose_name='Optionaler Zusatzpunkt (Chiron/Pholus/Lilith)')),
            ],
            options={
                'verbose_name': 'Planet',
                'verbose_name_plural': 'Planeten',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Schlüssel')),
                ('name_de', models.CharField(max_length=50, verbose_name='Name')),
                ('symbol', models.CharField(blank=True, max_length=5, verbose_name='Symbol')),
                ('element', models.CharField(choices=[('feuer', 'Feuer'), ('erde', 'Erde'), ('luft', 'Luft'), ('wasser', 'Wasser')], max_length=20, verbose_name='Element')),
                ('quality', models.CharField(choices=[('kardinal', 'Kardinal'), ('fix', 'Fix'), ('veraenderlich', 'Veränderlich')], max_length=20, verbose_name='Qualität')),
                ('ruling_planet_key', models.CharField(blank=True, max_length=20, verbose_name='Herrscherplanet (Schlüssel)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sortierung')),
            ],
            options={
                'verbose_name': 'Tierkreiszeichen',
                'verbose_name_plural': 'Tierkreiszeichen',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(blank=True, max_length=100, verbose_name='Bestellreferenz')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10, verbose_name='Format')),
                ('file', models.FileField(upload_to='astro_reports/%Y/%m/', verbose_name='Datei')),
                ('chart_wheel_svg', models.FileField(blank=True, null=True, upload_to='astro_charts/%Y/%m/', verbose_name='Horoskoprad (SVG)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='astro.birthchart', verbose_name='Geburtshoroskop')),
            ],
            options={
                'verbose_name': 'Erstellter Report',
                'verbose_name_plural': 'Erstellte Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='birthchart',
            name='moon_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.house', verbose_name='Mondhaus'),
        ),
        migrations.AddField(
            model_name='birthchart',
            name='sun_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.house', verbose_name='Sonnenhaus'),
        ),
        migrations.CreateModel(
            name='GemstoneCorrespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heilstein_ref', models.CharField(max_length=100, verbose_name='Heilstein-Referenz')),
                ('role', models.CharField(choices=[('hauptstein', 'Hauptstein'), ('ergaenzungsstein', 'Ergänzungsstein')], max_length=50, verbose_name='Rolle')),
                ('note', models.TextField(blank=True, verbose_name='Hinweis')),
                ('planet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='astro.planet', verbose_name='Planet')),
                ('sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='astro.zodiacsign', verbose_name='Zeichen')),
            ],
            options={
                'verbose_name': 'Heilstein-Zuordnung',
                'verbose_name_plural': 'Heilstein-Zuordnungen',
            },
        ),
        migrations.CreateModel(
            name='CombinationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Text')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('reviewed', 'Geprüft'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('planet_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.planet', verbose_name='Planet A')),
                ('planet_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.planet', verbose_name='Planet B')),
                ('sign_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Zeichen A')),
                ('sign_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Zeichen B')),
            ],
            options={
                'verbose_name': 'Kombinationstext',
                'verbose_name_plural': 'Kombinationstexte',
            },
        ),
        migrations.AddField(
            model_name='birthchart',
            name='ascendant_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Aszendent'),
        ),
        migrations.AddField(
            model_name='birthchart',
            name='mc_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Medium Coeli (MC)'),
        ),
        migrations.AddField(
            model_name='birthchart',
            name='moon_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Mondzeichen'),
        ),
        migrations.AddField(
            model_name='birthchart',
            name='sun_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Sonnenzeichen'),
        ),
        migrations.CreateModel(
            name='InterpretationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_type', models.CharField(choices=[('grund', 'Grundtext'), ('konstruktiv', 'Konstruktive Seiten'), ('problematisch', 'Problematische Seiten'), ('beruf', 'Beruf'), ('beziehung', 'Liebe/Partnerschaft'), ('kindheit', 'Kindheit'), ('heilstein_intro', 'Heilstein-Einleitung')], max_length=20, verbose_name='Textart')),
                ('body', models.TextField(verbose_name='Text')),
                ('source_notes', models.TextField(blank=True, verbose_name='Quellen-Notiz (intern)')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('reviewed', 'Geprüft'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Verfasst von')),
                ('reviewed_by', models.CharField(blank=True, max_length=100, verbose_name='Geprüft von')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='astro.house', verbose_name='Haus')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astro.planet', verbose_name='Planet')),
                ('sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='astro.zodiacsign', verbose_name='Zeichen')),
            ],
            options={
                'verbose_name': 'Auswertungstext',
                'verbose_name_plural': 'Auswertungstexte',
                'unique_together': {('planet', 'sign', 'house', 'text_type')},
            },
        ),
    ]
