# Generated by Django 5.2.16 on 2026-07-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True, verbose_name='Suchanfrage')),
                ('geonameid', models.CharField(blank=True, max_length=20, verbose_name='GeoNames-ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Ortsname')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Land')),
                ('lat', models.FloatField(verbose_name='Breitengrad')),
                ('lon', models.FloatField(verbose_name='Längengrad')),
                ('timezone', models.CharField(blank=True, max_length=64, verbose_name='Zeitzone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Geocode-Cache-Eintrag',
                'verbose_name_plural': 'Geocode-Cache-Einträge',
            },
        ),
    ]
