# Generated by Django 5.2.16 on 2026-07-18 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0004_seed_mondknoten'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemenBild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField(blank=True, null=True, verbose_name='Bilddaten')),
                ('content_type', models.CharField(default='image/png', editable=False, max_length=50, verbose_name='Content-Type')),
                ('topic', models.CharField(choices=[('liebe', 'Liebe/Partnerschaft'), ('kind', 'Kindheit')], max_length=20, unique=True, verbose_name='Thema')),
            ],
            options={
                'verbose_name': 'Themenbild',
                'verbose_name_plural': 'Themenbilder',
            },
        ),
        migrations.AlterUniqueTogether(
            name='interpretationtext',
            unique_together={('planet', 'sign', 'text_type')},
        ),
        migrations.RemoveField(
            model_name='zodiacsign',
            name='ruling_planet_key',
        ),
        migrations.AddField(
            model_name='zodiacsign',
            name='ruler_planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.planet', verbose_name='Herrscherplanet'),
        ),
        migrations.AddField(
            model_name='zodiacsign',
            name='symbol_image',
            field=models.BinaryField(blank=True, null=True, verbose_name='Symbolbild'),
        ),
        migrations.AddField(
            model_name='zodiacsign',
            name='symbol_image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='Symbolbild-Content-Type'),
        ),
        migrations.AlterField(
            model_name='interpretationtext',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astro.zodiacsign', verbose_name='Zeichen'),
        ),
        migrations.AlterField(
            model_name='interpretationtext',
            name='text_type',
            field=models.CharField(choices=[('grund', 'Allgemeine Beschreibung (Grundtext)'), ('konstruktiv', 'Der konstruktive [Zeichen]'), ('problematisch', 'Der problematische [Zeichen]'), ('gegenteil', 'Das Gegenteil der Eigenschaften'), ('beziehung', 'Freundschaft/Partnerschaft/Liebe'), ('beruf', 'Beruf'), ('kindheit', 'Kindheit'), ('aufgaben_karma', 'Aufgaben/Karma/Gesundheit'), ('entsprechungen', 'Entsprechungen'), ('erfuellt', 'Die erfüllte Seite'), ('unerfuellt', 'Die unerfüllte Seite'), ('psychologisches', 'Psychologisches'), ('gesundheit', 'Gesundheit (Kurzform)')], max_length=20, verbose_name='Textart'),
        ),
        migrations.CreateModel(
            name='HausherrAszendentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('reviewed', 'Geprüft'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Verfasst von')),
                ('reviewed_by', models.CharField(blank=True, max_length=100, verbose_name='Geprüft von')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('body', models.TextField(help_text='Kompletter Block: Titel + Formel + Einleitung + Charakterabsatz', verbose_name='Text')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astro.house', verbose_name='Haus')),
                ('sign_aszendent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Aszendentzeichen')),
            ],
            options={
                'verbose_name': 'Hausherr-Aszendent-Text',
                'verbose_name_plural': 'Hausherr-Aszendent-Texte',
                'unique_together': {('sign_aszendent', 'house')},
            },
        ),
        migrations.CreateModel(
            name='ShortDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('reviewed', 'Geprüft'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Verfasst von')),
                ('reviewed_by', models.CharField(blank=True, max_length=100, verbose_name='Geprüft von')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('body', models.TextField(verbose_name='Text')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astro.planet', verbose_name='Planet')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astro.zodiacsign', verbose_name='Zeichen')),
            ],
            options={
                'verbose_name': 'Kurzbeschreibung',
                'verbose_name_plural': 'Kurzbeschreibungen',
                'unique_together': {('planet', 'sign')},
            },
        ),
        migrations.CreateModel(
            name='SonneAszendentKombiText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('reviewed', 'Geprüft'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Verfasst von')),
                ('reviewed_by', models.CharField(blank=True, max_length=100, verbose_name='Geprüft von')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('body', models.TextField(help_text='Kompletter Block: Kurztext + Chance/Herausforderung', verbose_name='Text')),
                ('sign_aszendent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Aszendentzeichen')),
                ('sign_sonne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Sonnenzeichen')),
            ],
            options={
                'verbose_name': 'Sonne-Aszendent-Kombination',
                'verbose_name_plural': 'Sonne-Aszendent-Kombinationen',
                'unique_together': {('sign_sonne', 'sign_aszendent')},
            },
        ),
        migrations.CreateModel(
            name='SonneMondKombiText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('reviewed', 'Geprüft'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Verfasst von')),
                ('reviewed_by', models.CharField(blank=True, max_length=100, verbose_name='Geprüft von')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('kombi_text', models.TextField(help_text='Freier Fließtext, Einleitung des Kapitels', verbose_name='Einleitungstext')),
                ('sonne_charakter', models.TextField(verbose_name='Sonne: Charakter')),
                ('sonne_lernt', models.TextField(verbose_name='Sonne: Lernt')),
                ('sonne_muss', models.TextField(verbose_name='Sonne: Muss')),
                ('sonne_liebe', models.TextField(verbose_name='Sonne: Liebe')),
                ('sonne_astrologik', models.TextField(verbose_name='Sonne: Astrologik')),
                ('mond_charakter', models.TextField(verbose_name='Mond: Charakter')),
                ('mond_lernt', models.TextField(verbose_name='Mond: Lernt')),
                ('mond_muss', models.TextField(verbose_name='Mond: Muss')),
                ('mond_liebe', models.TextField(verbose_name='Mond: Liebe')),
                ('mond_astrologik', models.TextField(verbose_name='Mond: Astrologik')),
                ('sign_mond', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Mondzeichen')),
                ('sign_sonne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='astro.zodiacsign', verbose_name='Sonnenzeichen')),
            ],
            options={
                'verbose_name': 'Sonne-Mond-Kombination',
                'verbose_name_plural': 'Sonne-Mond-Kombinationen',
                'unique_together': {('sign_sonne', 'sign_mond')},
            },
        ),
        migrations.DeleteModel(
            name='CombinationText',
        ),
        migrations.RemoveField(
            model_name='interpretationtext',
            name='house',
        ),
    ]
