# Generated by Django 5.2.16 on 2026-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0006_seed_ruler_planet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_background', models.ImageField(upload_to='astro/branding/', verbose_name='Deckblatt-Hintergrund')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Report-Branding',
                'verbose_name_plural': 'Report-Branding',
            },
        ),
        migrations.RemoveField(
            model_name='zodiacsign',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='zodiacsign',
            name='symbol_image',
        ),
        migrations.RemoveField(
            model_name='zodiacsign',
            name='symbol_image_content_type',
        ),
        migrations.AddField(
            model_name='zodiacsign',
            name='symbol_image_png',
            field=models.BinaryField(blank=True, null=True, verbose_name='Symbolbild (PNG)'),
        ),
        migrations.AddField(
            model_name='zodiacsign',
            name='symbol_image_svg',
            field=models.BinaryField(blank=True, null=True, verbose_name='Symbolbild (SVG)'),
        ),
        migrations.AddField(
            model_name='zodiacsign',
            name='zodiac_image_png',
            field=models.BinaryField(blank=True, null=True, verbose_name='Zeichenbild (PNG)'),
        ),
        migrations.AddField(
            model_name='zodiacsign',
            name='zodiac_image_svg',
            field=models.BinaryField(blank=True, null=True, verbose_name='Zeichenbild (SVG)'),
        ),
    ]
