# Generated by Django 5.2.16 on 2026-07-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0007_reportbranding_remove_zodiacsign_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportbranding',
            name='cover_background',
        ),
        migrations.RemoveField(
            model_name='reportbranding',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='reportbranding',
            name='content_type',
            field=models.CharField(default='image/png', editable=False, max_length=50, verbose_name='Content-Type'),
        ),
        migrations.AddField(
            model_name='reportbranding',
            name='image_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Bilddaten'),
        ),
    ]
