# Generated by Django 5.2.16 on 2026-07-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0009_zodiacsign_dative_phrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetHouseText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('reviewed', 'Geprüft'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Verfasst von')),
                ('reviewed_by', models.CharField(blank=True, max_length=100, verbose_name='Geprüft von')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('body', models.TextField(verbose_name='Text')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astro.house', verbose_name='Haus')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astro.planet', verbose_name='Planet')),
            ],
            options={
                'verbose_name': 'Planet-im-Haus-Text',
                'verbose_name_plural': 'Planet-im-Haus-Texte',
                'unique_together': {('planet', 'house')},
            },
        ),
    ]
