# Generated by Django 5.2.16 on 2026-07-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0010_planethousetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretationtext',
            name='heading',
            field=models.CharField(blank=True, help_text='Erscheint als Zwischenüberschrift im Report. Leer lassen für keine Überschrift.', max_length=200, verbose_name='Überschrift'),
        ),
    ]
