# Generated by Django 5.2.16 on 2026-07-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(default='EUR', max_length=3)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('shop_url', models.URLField(blank=True)),
                ('purchase_price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_price_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('purchase_price_unit_label', models.CharField(blank=True, max_length=20)),
                ('variant_label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.article')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='contacts.supplier')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
