# Generated by Django 5.2.16 on 2026-07-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_article_archived_at_article_is_archived'),
        ('contacts', '0003_alter_customer_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterField(
            model_name='article',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='article',
            name='currency_code',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Währung'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv gelistet'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archiviert'),
        ),
        migrations.AlterField(
            model_name='article',
            name='minimum_stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Soll-Lagerbestand'),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.article', verbose_name='Hauptartikel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='article',
            name='purchase_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Einkaufspreis (Grundpreis)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='purchase_price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Einkaufspreis (gesamt)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='purchase_price_unit_label',
            field=models.CharField(blank=True, max_length=20, verbose_name='Grundpreis-Einheit'),
        ),
        migrations.AlterField(
            model_name='article',
            name='shop_url',
            field=models.URLField(blank=True, verbose_name='Shop-Link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Lagerbestand'),
        ),
        migrations.AlterField(
            model_name='article',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='contacts.supplier', verbose_name='Lieferant'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='Vorschaubild-URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='article',
            name='variant_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Variante'),
        ),
    ]
