# Generated by Django 5.2.16 on 2026-07-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_article_options_alter_article_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kategorie'),
        ),
    ]
