# Generated by Django 5.2.16 on 2026-07-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='purchase_price_total',
        ),
        migrations.AddField(
            model_name='article',
            name='purchase_price_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Einkaufspreis pro Stück'),
        ),
        migrations.AlterField(
            model_name='article',
            name='purchase_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Grundpreis'),
        ),
    ]
