# Generated by Django 5.2.16 on 2026-07-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_article_purchase_price_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyListingMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=50, unique=True, verbose_name='Etsy-Listing-ID')),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='Etsy-Artikelname')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_mappings', to='catalog.article', verbose_name='Artikel')),
            ],
            options={
                'verbose_name': 'Etsy-Listing-Zuordnung',
                'verbose_name_plural': 'Etsy-Listing-Zuordnungen',
                'ordering': ['item_name'],
            },
        ),
    ]
