# Generated by Django 5.2.16 on 2026-07-15 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_etsylistingmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_sold_out',
            field=models.BooleanField(default=False, verbose_name='Ausverkauft'),
        ),
    ]
