# Generated by Django 5.2.16 on 2026-07-11 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0004_split_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('is_all_day', models.BooleanField(default=True, verbose_name='Ganztägig')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Startzeit')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('event_type', models.CharField(blank=True, max_length=50, verbose_name='Termin-Typ')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ort')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='contacts.customer', verbose_name='Kunde')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='contacts.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
