# Generated by Django 5.2.16 on 2026-07-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('contacts', '0004_split_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='contacts.customer', verbose_name='Kunden'),
        ),
    ]
