# Generated by Django 5.2.16 on 2026-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_customer_appointment_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='has_reminder',
            field=models.BooleanField(default=False, verbose_name='Erinnerung'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_dismissed',
            field=models.BooleanField(default=False, verbose_name='Erinnerung verworfen'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_lead_minutes',
            field=models.PositiveIntegerField(blank=True, choices=[(5, '5 Minuten vorher'), (15, '15 Minuten vorher'), (30, '30 Minuten vorher'), (60, '1 Stunde vorher'), (120, '2 Stunden vorher'), (1440, '1 Tag vorher')], default=30, null=True, verbose_name='Vorlaufzeit'),
        ),
    ]
