# Generated by Django 5.2.16 on 2026-07-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_referenceoption_options_and_more'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wunschlisten-Eintrag', 'verbose_name_plural': 'Wunschlisten-Einträge'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitemimage',
            options={'ordering': ['item', 'position'], 'verbose_name': 'Wunschlisten-Bild', 'verbose_name_plural': 'Wunschlisten-Bilder'},
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Geschätzter Preis'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Link zum Angebot'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='status',
            field=models.CharField(blank=True, default='Idee', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'wishlist_tag'}, related_name='wishlist_items', to='core.referenceoption', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='wishlistitemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist/', verbose_name='Bild (Upload)'),
        ),
        migrations.AlterField(
            model_name='wishlistitemimage',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Bild-Link'),
        ),
        migrations.AlterField(
            model_name='wishlistitemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wishlist.wishlistitem', verbose_name='Eintrag'),
        ),
        migrations.AlterField(
            model_name='wishlistitemimage',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Reihenfolge'),
        ),
    ]
