# Generated by Django 5.2.16 on 2026-07-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_wishlistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inspirationboard-Eintrag', 'verbose_name_plural': 'Inspirationboard-Einträge'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitemimage',
            options={'ordering': ['item', 'position'], 'verbose_name': 'Inspirationboard-Bild', 'verbose_name_plural': 'Inspirationboard-Bilder'},
        ),
    ]
